#!/bin/bash
#python setup.py install --prefix=$prefix

usage()
{
cat << EOF
LIBBBG installation script

usage: $0 options

OPTIONS:
   -h      Show this message
   -p      prefix (default \usr\local)
   -x      exec_prefix (default \usr\local)
   -v      Verbose
   -V      Python version (2 or 3; default 3)

NOTES:
   if only prefix chosen, the exec_prefix will be the same as prefix
EOF
}

# installation variables
PREFIX=
EXEC_PREFIX=
VERBOSE=
PYTHONVERSION=3

# gather options
while getopts “hp:x:vV:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         p)
             PREFIX=$OPTARG
             ;;
         x)
             EXEC_PREFIX=$OPTARG
             ;;
         v)
             VERBOSE=1
             ;;
         V)
             PYTHONVERSION=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

# Python version
if [ "$PYTHONVERSION" = 3 ]
then
     python_compiler=python3
     f2py_compiler=f2py3
else
     python_compiler=python2
     f2py_compiler=f2py
fi

# if prefix is not set, set it to /usr/local
if [[ -z $PREFIX ]]
then
     EXEC_PREFIX=/usr/local
fi

# if exec-prefix is not set, set it up the same as prefix
if [[ -z $EXEC_PREFIX ]]
then
     EXEC_PREFIX=$PREFIX
fi

if [[ -z $PREFIX ]] || [[ -z $EXEC_PREFIX ]]
then
     echo Nothing to do. Run with -h option
     exit 1
fi

# install LIBBBG
$python_compiler setup.py install --prefix=$PREFIX --exec-prefix=$EXEC_PREFIX

# the shared libraries
export LIBBBG_LIB=$PREFIX/lib/python3.6/site-packages/

# install solpol and solpol2 extensions - requires mathematical libraries linked to NumPy!
cd libbbg/qm
$f2py_compiler -c --quiet --link-lapack_opt --link-blas_opt -m make_points  make_points.f
$f2py_compiler -c --quiet --link-lapack_opt --link-blas_opt -m wfn  wfn.f
mv -v $PWD/make_points.*.so $LIBBBG_LIB/libbbg/qm/make_points.so
mv -v $PWD/wfn.*.so $LIBBBG_LIB/libbbg/qm/wfn.so
cd ../..

echo --- INFO ---------------------------------------------------------------------------
echo
echo Modify your $HOME/.bashrc script adding the following line:
echo
echo export PYTHONPATH=$LIBBBG_LIB:'$PYTHONPATH'
echo
echo Then, type in the terminal
echo
echo source $HOME/.bashrc
echo
echo ------------------------------------------------------------------------------------

